# Assignment 04 - Pandas

## Company Data Analysis

In this assignment, you will work with the `company_data.csv` dataset to practice various Pandas operations including data loading, cleaning, filtering, and analysis.

**Instructions:** Complete each task by writing your code in the empty cells provided below each question.

## Task 1: Data Loading & Inspection

Load the `company_data.csv` file into a Pandas DataFrame.

**Requirements:**
- Print the first 10 rows of the dataset
- Use a Pandas method to show the data types of each column
- Check for missing values in each column

In [72]:
import pandas as pd

In [73]:
df = pd.read_csv("/content/company_data.csv")
df.head(10)

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus
0,101,John Doe,IT,85000.0,5,88,5000.0
1,102,Jane Smith,HR,60000.0,3,72,3000.0
2,103,Ali Mansour,Sales,NaN,12,95,7000.0
3,104,Sara Lee,IT,95000.0,1,45,NaN
4,105,Ben Clark,Finance,70000.0,8,60,4000.0
5,106,Eva Green,Sales,55000.0,4,82,2000.0
6,107,Mona Ray,HR,NaN,2,55,NaN
7,108,Leo King,IT,105000.0,10,91,8000.0
8,109,Tom Cook,Finance,72000.0,6,78,4500.0
9,110,Anna Bell,IT,88000.0,9,40,2500.0

In [74]:
df.dtypes

Employee_ID           int64
Employee_Name        object
Department           object
Salary              float64
Years_Experience      int64
Evaluation_Score      int64
Bonus               float64
dtype: object

In [75]:
df.isna().sum()

Employee_ID         0
Employee_Name       0
Department          0
Salary              2
Years_Experience    0
Evaluation_Score    0
Bonus               2
dtype: int64

In [76]:
df.describe()

,Employee_ID,Salary,Years_Experience,Evaluation_Score,Bonus
count,20.00000,18.000000,20.000000,20.000000,18.000000
mean,110.50000,76555.555556,6.150000,72.050000,4366.666667
std,5.91608,18036.636644,3.910512,18.588267,2271.563338
min,101.00000,54000.000000,1.000000,30.000000,1000.000000
25%,105.75000,60500.000000,3.000000,63.750000,2625.000000
50%,110.50000,73500.000000,5.500000,75.500000,4250.000000
75%,115.25000,91000.000000,9.000000,85.750000,5750.000000
max,120.00000,110000.000000,15.000000,98.000000,9000.000000

## Task 2: Handling Missing Values

The dataset contains missing values in the `Salary` and `Bonus` columns.

**Requirements:**
- Fill the missing `Salary` values with the median salary of the entire company
- Fill the missing `Bonus` values with 0

In [77]:
df['Salary'] =  df['Salary'].fillna(df['Salary'].mean())

In [78]:
df.isna().sum()

Employee_ID         0
Employee_Name       0
Department          0
Salary              0
Years_Experience    0
Evaluation_Score    0
Bonus               2
dtype: int64

In [79]:
df['Bonus'] = df['Bonus'].fillna(0)

In [80]:
df.isna().sum()

Employee_ID         0
Employee_Name       0
Department          0
Salary              0
Years_Experience    0
Evaluation_Score    0
Bonus               0
dtype: int64

## Task 3: Data Cleaning

The `Employee_Name` column is in the format "FirstName LastName".

**Requirements:**
- Split this column into two new columns: `First_Name` and `Last_Name`
- Delete the original `Employee_Name` column

In [81]:
df['Employee_Name'] = df['Employee_Name'].map(lambda x: x.split() )
df['Employee_Name']

0         [John, Doe]
1       [Jane, Smith]
2      [Ali, Mansour]
3         [Sara, Lee]
4        [Ben, Clark]
5        [Eva, Green]
6         [Mona, Ray]
7         [Leo, King]
8         [Tom, Cook]
9        [Anna, Bell]
10        [Ryan, Gos]
11      [Emma, Stone]
12      [Will, Smith]
13       [Kate, Wins]
14       [Jack, Spar]
15     [Bruce, Wayne]
16      [Clark, Kent]
17    [Diana, Prince]
18     [Barry, Allen]
19      [Hal, Jordan]
Name: Employee_Name, dtype: object

In [82]:
df['First_Name']= df['Employee_Name'].map(lambda x: x[0] )
df['Last_Name'] = df['Employee_Name'].map(lambda x: x[1] )
df.head()

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
0,101,"[John, Doe]",IT,85000.000000,5,88,5000.0,John,Doe
1,102,"[Jane, Smith]",HR,60000.000000,3,72,3000.0,Jane,Smith
2,103,"[Ali, Mansour]",Sales,76555.555556,12,95,7000.0,Ali,Mansour
3,104,"[Sara, Lee]",IT,95000.000000,1,45,0.0,Sara,Lee
4,105,"[Ben, Clark]",Finance,70000.000000,8,60,4000.0,Ben,Clark

In [83]:
df = df.drop("Employee_Name" , axis=1)
df.head()

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
0,101,IT,85000.000000,5,88,5000.0,John,Doe
1,102,HR,60000.000000,3,72,3000.0,Jane,Smith
2,103,Sales,76555.555556,12,95,7000.0,Ali,Mansour
3,104,IT,95000.000000,1,45,0.0,Sara,Lee
4,105,Finance,70000.000000,8,60,4000.0,Ben,Clark

## Task 4: Filtering

Create a new DataFrame called `Senior_IT`.

**Requirements:**
- The DataFrame should contain only employees from the 'IT' department
- These employees must have more than 8 years of experience

In [84]:
Senior_IT = df[ df['Department']=='IT'  ]
Senior_IT.head()

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
0,101,IT,85000.0,5,88,5000.0,John,Doe
3,104,IT,95000.0,1,45,0.0,Sara,Lee
7,108,IT,105000.0,10,91,8000.0,Leo,King
9,110,IT,88000.0,9,40,2500.0,Anna,Bell
12,113,IT,92000.0,11,77,6000.0,Will,Smith

In [85]:
Senior_IT =  Senior_IT[df['Years_Experience']>=8]
Senior_IT.head()

/tmp/ipykernel_376/706617211.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  Senior_IT =  Senior_IT[df['Years_Experience']>=8]

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
7,108,IT,105000.0,10,91,8000.0,Leo,King
9,110,IT,88000.0,9,40,2500.0,Anna,Bell
12,113,IT,92000.0,11,77,6000.0,Will,Smith
15,116,IT,110000.0,15,98,9000.0,Bruce,Wayne
18,119,IT,98000.0,9,81,6500.0,Barry,Allen

In [86]:
Senior_IT.shape

(5, 8)

## Task 5: Performance Mapping

Create a new column called `Performance_Level` based on the `Evaluation_Score` (1-100).

**Requirements:**
- Score > 80: "High"
- Score 50-80: "Medium"
- Score < 50: "Low"

In [87]:
df['Performance_Level'] = df['Evaluation_Score'].map(lambda x: "High" if x>80 else "Medium" if x>50 else "Low")
df

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name,Performance_Level
0,101,IT,85000.000000,5,88,5000.0,John,Doe,High
1,102,HR,60000.000000,3,72,3000.0,Jane,Smith,Medium
2,103,Sales,76555.555556,12,95,7000.0,Ali,Mansour,High
3,104,IT,95000.000000,1,45,0.0,Sara,Lee,Low
4,105,Finance,70000.000000,8,60,4000.0,Ben,Clark,Medium
5,106,Sales,55000.000000,4,82,2000.0,Eva,Green,High
6,107,HR,76555.555556,2,55,0.0,Mona,Ray,Medium
7,108,IT,105000.000000,10,91,8000.0,Leo,King,High
8,109,Finance,72000.000000,6,78,4500.0,Tom,Cook,Medium
9,110,IT,88000.000000,9,40,2500.0,Anna,Bell,Low
10,111,Sales,58000.000000,2,65,1500.0,Ryan,Gos,Medium
11,112,HR,62000.000000,5,89,3500.0,Emma,Stone,High
12,113,IT,92000.000000,11,77,6000.0,Will,Smith,Medium
13,114,Sales,54000.000000,1,30,1000.0,Kate,Wins,Low
14,115,Finance,75000.000000,7,85,5000.0,Jack,Spar,High
15,116,IT,110000.000000,15,98,9000.0,Bruce,Wayne,High
16,117,HR,63000.000000,4,70,3200.0,Clark,Kent,Medium
17,118,Sales,59000.000000,3,66,2100.0,Diana,Prince,Medium
18,119,IT,98000.000000,9,81,6500.0,Barry,Allen,High
19,120,Finance,77000.000000,6,74,4800.0,Hal,Jordan,Medium

In [88]:
Senior_IT['Performance_Level'] = Senior_IT['Evaluation_Score'].map(lambda x: "High" if x>80 else "Medium" if x>50 else "Low")
Senior_IT

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name,Performance_Level
7,108,IT,105000.0,10,91,8000.0,Leo,King,High
9,110,IT,88000.0,9,40,2500.0,Anna,Bell,Low
12,113,IT,92000.0,11,77,6000.0,Will,Smith,Medium
15,116,IT,110000.0,15,98,9000.0,Bruce,Wayne,High
18,119,IT,98000.0,9,81,6500.0,Barry,Allen,High

## Task 6: Department Statistics

Calculate statistics for each Department.

**Requirements:**
- Calculate the total salary expense for each department
- Calculate the average evaluation score for each department

In [89]:
departments = df['Department'].unique()
departments

array(['IT', 'HR', 'Sales', 'Finance'], dtype=object)

In [90]:
total_department = df.groupby("Department")['Salary'].sum()
total_department

Department
Finance    294000.000000
HR         261555.555556
IT         673000.000000
Sales      302555.555556
Name: Salary, dtype: float64

In [91]:
avg_department = df.groupby("Department")['Salary'].mean()
avg_department

Department
Finance    73500.000000
HR         65388.888889
IT         96142.857143
Sales      60511.111111
Name: Salary, dtype: float64

## Task 7: Top Earners

Find the top 5 highest-paid employees in the company.

**Requirements:**
- Print only their names and salaries

In [92]:
highest = df.sort_values(by='Salary' , ascending=False).head()
highest[['First_Name','Last_Name','Salary']]

   First_Name Last_Name    Salary
15      Bruce     Wayne  110000.0
7         Leo      King  105000.0
18      Barry     Allen   98000.0
3        Sara       Lee   95000.0
12       Will     Smith   92000.0

## Task 8: Salary Update

The company is giving a 10% raise to everyone in the 'Sales' department.

**Requirements:**
- Update the `Salary` column for Sales department employees only
- Apply a 10% increase to their current salary

In [93]:
df['Salary'][df['Department'] == "Sales"].map(lambda x: x*(1+10/100))

2     84211.111111
5     60500.000000
10    63800.000000
13    59400.000000
17    64900.000000
Name: Salary, dtype: float64

In [94]:
df.loc[df['Department']=="Sales","Salary"] = df.loc[df['Department']=="Sales","Salary"] * (1+10/100)

In [95]:
df.loc[df['Department']=="Sales","Salary"]

2     84211.111111
5     60500.000000
10    63800.000000
13    59400.000000
17    64900.000000
Name: Salary, dtype: float64

In [97]:
df[df['Department']=="Sales"]

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name,Performance_Level
2,103,Sales,84211.111111,12,95,7000.0,Ali,Mansour,High
5,106,Sales,60500.000000,4,82,2000.0,Eva,Green,High
10,111,Sales,63800.000000,2,65,1500.0,Ryan,Gos,Medium
13,114,Sales,59400.000000,1,30,1000.0,Kate,Wins,Low
17,118,Sales,64900.000000,3,66,2100.0,Diana,Prince,Medium

## Task 9: Exporting Results

Save the final, cleaned, and updated DataFrame.

**Requirements:**
- Export the DataFrame to a new CSV file
- Name the file `final_employee_report.csv`

In [98]:
df.to_csv("final_employee_report.csv")